// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Undersoft.SVC.Service.Infrastructure.Stores;

#nullable disable

namespace Undersoft.SVC.Service.Infrastructure.Stores.Migrations.Accounts
{
    [DbContext(typeof(AccountStore))]
    partial class AccountStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Accounts")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<long>("AccountsId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.HasKey("AccountsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("AccountRole", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Access.Credentials", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Authenticated")
                        .HasColumnType("boolean");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<bool>("CookiesConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<string>("NewPassword")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("OldPassword")
                        .HasColumnType("text");

                    b.Property<bool>("OptionalConsent")
                        .HasColumnType("boolean");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberConfirmationToken")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RegistrationCompleteToken")
                        .HasColumnType("text");

                    b.Property<bool>("RegistrationCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ReturnPath")
                        .HasColumnType("text");

                    b.Property<string>("RetypedPassword")
                        .HasColumnType("text");

                    b.Property<bool>("SaveAccountInCookies")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text");

                    b.Property<int?>("Site")
                        .HasColumnType("integer");

                    b.Property<bool>("TermsConsent")
                        .HasColumnType("boolean");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Credentials", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Operation.OperationNotes", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<string>("Current")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Success")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("OperationNotes", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Authenticated")
                        .HasColumnType("boolean");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<long?>("ConsentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<long?>("CredentialsId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long?>("NotesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProfessionalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubscriptionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("ConsentId")
                        .IsUnique();

                    b.HasIndex("CredentialsId");

                    b.HasIndex("NotesId");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.HasIndex("ProfessionalId")
                        .IsUnique();

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Accounts", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountAddress", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Apartment")
                        .HasColumnType("text");

                    b.Property<string>("Building")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("GetState")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountAddreses", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountClaims", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AccountLogins", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountOrganization", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<string>("OrganizationFullName")
                        .HasColumnType("text");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrganizationImage")
                        .HasColumnType("text");

                    b.Property<byte[]>("OrganizationImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("OrganizationIndustry")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationSize")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationWebsites")
                        .HasColumnType("text");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("PositionInOrganization")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("AccountOrganizations", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountPersonal", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("SocialMedia")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.Property<string>("Websites")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountPersonals", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountProfessional", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionIndustry")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalEmail")
                        .HasColumnType("text");

                    b.Property<float>("ProfessionalExperience")
                        .HasColumnType("real");

                    b.Property<string>("ProfessionalPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalSocialMedia")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalWebsites")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountProffesionals", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("RegistrationCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AccountUsers", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.Organization", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<string>("OrganizationFullName")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationImage")
                        .HasColumnType("text");

                    b.Property<byte[]>("OrganizationImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("OrganizationIndustry")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationSize")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationWebsites")
                        .HasColumnType("text");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("PositionInOrganization")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Organizations", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AccountRoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountRoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountConsent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<long?>("ConsentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketingText")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<bool>("PersonalDataConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonalDataText")
                        .HasColumnType("text");

                    b.Property<bool>("TermsConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("TermsText")
                        .HasColumnType("text");

                    b.Property<bool>("ThirdPartyConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("ThirdPartyText")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("ConsentId");

                    b.ToTable("AccountConsents", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountPayment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CardCSV")
                        .HasColumnType("text");

                    b.Property<string>("CardExpirationDate")
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .HasColumnType("text");

                    b.Property<string>("CardTitle")
                        .HasColumnType("text");

                    b.Property<string>("CardType")
                        .HasColumnType("text");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("PaymentFirstName")
                        .HasColumnType("text");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentImage")
                        .HasColumnType("text");

                    b.Property<byte[]>("PaymentImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("PaymentLastName")
                        .HasColumnType("text");

                    b.Property<string>("PaymentPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.Property<bool>("PaymentTermsConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<string>("PaymentWebsites")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.ToTable("AccountPayments", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.Consent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketingText")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<bool>("PersonalDataConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonalDataText")
                        .HasColumnType("text");

                    b.Property<bool>("TermsConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("TermsText")
                        .HasColumnType("text");

                    b.Property<bool>("ThirdPartyConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("ThirdPartyText")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Consents", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.Payment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("CardCSV")
                        .HasColumnType("text");

                    b.Property<string>("CardExpirationDate")
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .HasColumnType("text");

                    b.Property<string>("CardTitle")
                        .HasColumnType("text");

                    b.Property<string>("CardType")
                        .HasColumnType("text");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("PaymentFirstName")
                        .HasColumnType("text");

                    b.Property<string>("PaymentImage")
                        .HasColumnType("text");

                    b.Property<byte[]>("PaymentImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("PaymentLastName")
                        .HasColumnType("text");

                    b.Property<string>("PaymentPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.Property<bool>("PaymentTermsConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<string>("PaymentWebsites")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Payment", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("SubscriptionCurrency")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubscriptionExpireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubscriptionName")
                        .HasColumnType("text");

                    b.Property<double>("SubscriptionPeriod")
                        .HasColumnType("double precision");

                    b.Property<double>("SubscriptionQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("SubscriptionStatus")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionToken")
                        .HasColumnType("text");

                    b.Property<double>("SubscriptionValue")
                        .HasColumnType("double precision");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Subscriptions", "Accounts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.AccountTenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantName")
                        .HasColumnType("text");

                    b.Property<string>("TenantPath")
                        .HasColumnType("text");

                    b.Property<string>("TenantUrl")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("AccountTenants", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("CodeNo")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(8);

                    b.Property<string>("Creator")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(9);

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp")
                        .HasColumnOrder(6);

                    b.Property<string>("Modifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(7);

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<string>("TenantName")
                        .HasColumnType("text");

                    b.Property<string>("TenantPath")
                        .HasColumnType("text");

                    b.Property<string>("TenantUrl")
                        .HasColumnType("text");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("TypeName")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Tenants", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Tokens.AccountToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountTokens", "Accounts");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountSubscription", b =>
                {
                    b.HasBaseType("Undersoft.SDK.Service.Server.Accounts.Licensing.Subscription");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubscriptionId")
                        .HasColumnType("bigint");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("AccountSubscriptions", "Accounts");
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Account", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountAddress", "Address")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "AddressId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountConsent", "Consent")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "ConsentId");

                    b.HasOne("Undersoft.SDK.Service.Access.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("Undersoft.SDK.Service.Operation.OperationNotes", "Notes")
                        .WithMany()
                        .HasForeignKey("NotesId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountOrganization", "Organization")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "OrganizationId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountPayment", "Payment")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "PaymentId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountPersonal", "Personal")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "PersonalId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountProfessional", "Professional")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "ProfessionalId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountSubscription", "Subscription")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "SubscriptionId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.AccountTenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Account", "TenantId");

                    b.Navigation("Address");

                    b.Navigation("Consent");

                    b.Navigation("Credentials");

                    b.Navigation("Notes");

                    b.Navigation("Organization");

                    b.Navigation("Payment");

                    b.Navigation("Personal");

                    b.Navigation("Professional");

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountAddress", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Identity.AccountAddress", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountClaim", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountLogin", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountOrganization", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Identity.AccountOrganization", "AccountId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.Organization", "Organization")
                        .WithMany("AccountOrganizations")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Account");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountPersonal", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Identity.AccountPersonal", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountProfessional", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Identity.AccountProfessional", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.AccountRole", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.RoleClaim", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("AccountRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountConsent", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountConsent", "AccountId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.Consent", "Consent")
                        .WithMany("AccountConsents")
                        .HasForeignKey("ConsentId");

                    b.Navigation("Account");

                    b.Navigation("Consent");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountPayment", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountPayment", "AccountId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.Payment", "Payment")
                        .WithMany("AccountPayments")
                        .HasForeignKey("PaymentId");

                    b.Navigation("Account");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.AccountTenant", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.AccountTenant", "AccountId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.Tenant", "Tenant")
                        .WithMany("AccountTenants")
                        .HasForeignKey("TenantId");

                    b.Navigation("Account");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Tokens.AccountToken", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithMany("Tokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Identity.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountSubscription", b =>
                {
                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountSubscription", "AccountId");

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.Subscription", null)
                        .WithOne()
                        .HasForeignKey("Undersoft.SDK.Service.Server.Accounts.Licensing.AccountSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Undersoft.SDK.Service.Server.Accounts.Licensing.Subscription", "Subscription")
                        .WithMany("AccountSubscriptions")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Account");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Account", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.Organization", b =>
                {
                    b.Navigation("AccountOrganizations");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Identity.Role", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.Consent", b =>
                {
                    b.Navigation("AccountConsents");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.Payment", b =>
                {
                    b.Navigation("AccountPayments");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.Licensing.Subscription", b =>
                {
                    b.Navigation("AccountSubscriptions");
                });

            modelBuilder.Entity("Undersoft.SDK.Service.Server.Accounts.MultiTenancy.Tenant", b =>
                {
                    b.Navigation("AccountTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
